  version: 3

  tasks:
    git-push:
      desc: Git Add, Commit and Push
      cmds:
        - git pull
        - git status
        - git add .
        - git commit -m "{{.CLI_ARGS}}"
        - git push  